# Generated by Django 4.0 on 2021-12-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='testing.jpeg', upload_to='thumbnail', verbose_name='Picture'),
        ),
    ]
