# Generated by Django 4.0 on 2021-12-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
