# Generated by Django 4.0 on 2021-12-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='promote',
            field=models.BooleanField(default=False),
        ),
    ]
