# Generated by Django 4.0 on 2021-12-26 23:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_post_promote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='details',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
