# Generated by Django 4.0 on 2021-12-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_comment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='viewers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
