# Generated by Django 4.0 on 2021-12-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_post_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='viewers',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
